version: '2'
services: 
  stubby4j:
    image: bbranquinho/stubby4j-docker
    ports:
        - 8882:8882
    environment:
        STUBBY_PORT: 8882
    volumes:
        - ./stubby.yml:/usr/local/stubby.yml
  locusttest:
    build: .
    volumes: 
        - .:/locust:ro
    working_dir: /locust
    command: /usr/local/bin/python locustfile-tests.py
    environment: 
      - HOST=http://stubby4j:8882
    depends_on:
      - stubby4j